create database webadmin;

grant all privileges on webadmin.* to 'webadmin'@'%' identified by 'webadmin';

use webadmin;

/* CREATE */
CREATE TABLE `DASHBOARD` (
    `ID` VARCHAR(16) PRIMARY KEY,
    `NAME` VARCHAR(50),
    `ROW` TINYINT UNSIGNED NOT NULL DEFAULT 6,
    `COLUMN` TINYINT UNSIGNED NOT NULL DEFAULT 6
);
/* TEST TABLE */
CREATE TABLE `CHART` (
    `ID` INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    `TEST` VARCHAR(10) DEFAULT NULL,
    `NAME` VARCHAR(20) NOT NULL,
    `TYPE` VARCHAR(20) NOT NULL,
    `DATA_COUNT` TINYINT UNSIGNED NOT NULL
);
CREATE TABLE `DASHBOARD_LAYOUT` (
    `ID` INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    `X` SMALLINT UNSIGNED NOT NULL,
    `Y` SMALLINT UNSIGNED NOT NULL,
    `W` SMALLINT UNSIGNED NOT NULL,
    `H` SMALLINT UNSIGNED NOT NULL,
    `DASHBOARD_ID` VARCHAR(16) NOT NULL,
    `CHART_ID` INTEGER UNSIGNED NOT NULL,
    CONSTRAINT `FK_DASHBOARD_LAYOUT_DASHBARD_DASHBOARD_ID` FOREIGN KEY (`DASHBOARD_ID`) REFERENCES `DASHBOARD` (`ID`),
    CONSTRAINT `FK_DASHBOARD_LAYOUT_CHART_CHART_ID` FOREIGN KEY (`CHART_ID`) REFERENCES `CHART` (`ID`)
);
CREATE TABLE `NETWORK_MAP` (
    `ID` VARCHAR(16) PRIMARY KEY,
    `NAME` VARCHAR(50)
);
CREATE TABLE `WEB_USER` (
    `ID` VARCHAR(16) PRIMARY KEY,
    `USER_ID` VARCHAR(20) NOT NULL UNIQUE,
    `NAME` VARCHAR(50) NOT NULL,
    `PASSWORD` VARCHAR(100) NOT NULL,
    `EMAIL` VARCHAR(50) DEFAULT NULL,
    `PHONE` VARCHAR(13) DEFAULT NULL,
    `LAST_LOGIN` TIMESTAMP DEFAULT 0,
    `LAST_PASSWORD_CHANGE` TIMESTAMP DEFAULT 0,
    `LAST_LOGIN_FAIL` TIMESTAMP DEFAULT 0,
    `LOGIN_FAIL_COUNT` INTEGER UNSIGNED DEFAULT 0,
    `LOGIN_FAIL_IP` VARCHAR(15) DEFAULT NULL,
    `LOGIN_IP` VARCHAR(15) DEFAULT NULL,
    `ACCESS_IP` VARCHAR(15) DEFAULT '*',
    `DESCRIPTION` VARCHAR(500) DEFAULT NULL,
    `ROLE_ID` TINYINT UNSIGNED DEFAULT 3,
    `NETWORK_MAP_ID` VARCHAR(16) DEFAULT NULL,
    `DASHBOARD_ID` VARCHAR(16) DEFAULT NULL,
    CONSTRAINT `FK_WEB_USER_DASHBARD_DASHBOARD_ID` FOREIGN KEY (`DASHBOARD_ID`) REFERENCES `DASHBOARD` (`ID`),
    CONSTRAINT `FK_WEB_USER_NETWORK_MAP_NETWORK_MAP_ID` FOREIGN KEY (`NETWORK_MAP_ID`) REFERENCES `NETWORK_MAP` (`ID`)
);

/* ALTER */
ALTER TABLE `CHART` AUTO_INCREMENT = 1;
ALTER TABLE `DASHBOARD_LAYOUT` AUTO_INCREMENT = 1;

/* INSERT */
INSERT INTO `DASHBOARD` (`ID`, `NAME`, `ROW`, `COLUMN`) VALUES ('DBD0000000000000', '기본대시보드', 6, 6);
INSERT INTO `CHART` (`ID`, `TEST`, `NAME`, `TYPE`, `DATA_COUNT`) VALUES 
    (1, '1', 'Chart1', 'Column', 10), 
    (2, '2', 'Chart2', 'Pie', 2), 
    (3, '3', 'Chart3', 'Pie', 5), 
    (4, '4', 'Chart4', 'Pie', 3), 
    (5, '5', 'Chart5', 'Bar', 6), 
    (6, '6', 'Chart6', 'LineArea', 9), 
    (7, '7', 'Chart7', 'Column', 3);
INSERT INTO `DASHBOARD_LAYOUT` (`ID`, `X`, `Y`, `W`, `H`, `DASHBOARD_ID`, `CHART_ID`) VALUES 
    (1, 0, 0, 2, 3, 'DBD0000000000000', 1),
    (2, 2, 0, 1, 1, 'DBD0000000000000', 2),
    (3, 2, 1, 1, 1, 'DBD0000000000000', 3),
    (4, 2, 2, 1, 1, 'DBD0000000000000', 4),
    (5, 3, 0, 2, 2, 'DBD0000000000000', 5),
    (6, 3, 2, 2, 1, 'DBD0000000000000', 6),
    (7, 6, 0, 1, 3, 'DBD0000000000000', 7);
INSERT INTO `NETWORK_MAP` (`ID`, `NAME`) VALUES
    ('NWM0000000000000', '기본맵');

