version: '3.7'

services:
  mariadb-webadmin_node:
    image: mariadb:10.5.8
    container_name: mariadb-webadmin_node
    environment:
      - MYSQL_ROOT_PASSWORD=webadmin
      - MYSQL_DATABASE=webadmin_node
      - MYSQL_USER=webadmin
      - MYSQL_PASSWORD=webadmin
    volumes:
      - ./mariadb/data:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - webadmin_node-network
      
networks:
  webadmin_node-network:
    external: true

